/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.DockerExecutor');

goog.require('jspb.Message');
goog.require('proto.ga4gh_task_exec.Ports');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.DockerExecutor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ga4gh_task_exec.DockerExecutor.repeatedFields_, null);
};
goog.inherits(proto.ga4gh_task_exec.DockerExecutor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.DockerExecutor.displayName = 'proto.ga4gh_task_exec.DockerExecutor';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ga4gh_task_exec.DockerExecutor.repeatedFields_ = [2,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.DockerExecutor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.DockerExecutor} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.DockerExecutor.toObject = function(includeInstance, msg) {
  var f, obj = {
    imagename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cmdList: jspb.Message.getField(msg, 2),
    workdir: jspb.Message.getFieldWithDefault(msg, 3, ""),
    stdin: jspb.Message.getFieldWithDefault(msg, 6, ""),
    stdout: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stderr: jspb.Message.getFieldWithDefault(msg, 5, ""),
    portsList: jspb.Message.toObjectList(msg.getPortsList(),
    proto.ga4gh_task_exec.Ports.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string imageName = 1;
 * @return {string}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getImagename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setImagename = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated string cmd = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getCmdList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 2));
};


/** @param {!Array.<string>} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setCmdList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.addCmd = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.ga4gh_task_exec.DockerExecutor.prototype.clearCmdList = function() {
  this.setCmdList([]);
};


/**
 * optional string workdir = 3;
 * @return {string}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getWorkdir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setWorkdir = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string stdin = 6;
 * @return {string}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getStdin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setStdin = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string stdout = 4;
 * @return {string}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getStdout = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setStdout = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string stderr = 5;
 * @return {string}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getStderr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setStderr = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * repeated Ports ports = 7;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.Ports>}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.getPortsList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.Ports>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.Ports, 7));
};


/** @param {!Array.<!proto.ga4gh_task_exec.Ports>} value */
proto.ga4gh_task_exec.DockerExecutor.prototype.setPortsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.ga4gh_task_exec.Ports=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.Ports}
 */
proto.ga4gh_task_exec.DockerExecutor.prototype.addPorts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.ga4gh_task_exec.Ports, opt_index);
};


proto.ga4gh_task_exec.DockerExecutor.prototype.clearPortsList = function() {
  this.setPortsList([]);
};


