/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.JobLog');

goog.require('jspb.Message');
goog.require('proto.ga4gh_task_exec.Ports');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.JobLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ga4gh_task_exec.JobLog.repeatedFields_, null);
};
goog.inherits(proto.ga4gh_task_exec.JobLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.JobLog.displayName = 'proto.ga4gh_task_exec.JobLog';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ga4gh_task_exec.JobLog.repeatedFields_ = [1,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.JobLog.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.JobLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.JobLog} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.JobLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdList: jspb.Message.getField(msg, 1),
    starttime: jspb.Message.getFieldWithDefault(msg, 2, ""),
    endtime: jspb.Message.getFieldWithDefault(msg, 3, ""),
    stdout: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stderr: jspb.Message.getFieldWithDefault(msg, 5, ""),
    exitcode: jspb.Message.getFieldWithDefault(msg, 6, 0),
    hostip: jspb.Message.getFieldWithDefault(msg, 7, ""),
    portsList: jspb.Message.toObjectList(msg.getPortsList(),
    proto.ga4gh_task_exec.Ports.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * repeated string cmd = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.ga4gh_task_exec.JobLog.prototype.getCmdList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 1));
};


/** @param {!Array.<string>} value */
proto.ga4gh_task_exec.JobLog.prototype.setCmdList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.ga4gh_task_exec.JobLog.prototype.addCmd = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.ga4gh_task_exec.JobLog.prototype.clearCmdList = function() {
  this.setCmdList([]);
};


/**
 * optional string startTime = 2;
 * @return {string}
 */
proto.ga4gh_task_exec.JobLog.prototype.getStarttime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobLog.prototype.setStarttime = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string endTime = 3;
 * @return {string}
 */
proto.ga4gh_task_exec.JobLog.prototype.getEndtime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobLog.prototype.setEndtime = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string stdout = 4;
 * @return {string}
 */
proto.ga4gh_task_exec.JobLog.prototype.getStdout = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobLog.prototype.setStdout = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string stderr = 5;
 * @return {string}
 */
proto.ga4gh_task_exec.JobLog.prototype.getStderr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobLog.prototype.setStderr = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional int32 exitCode = 6;
 * @return {number}
 */
proto.ga4gh_task_exec.JobLog.prototype.getExitcode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.ga4gh_task_exec.JobLog.prototype.setExitcode = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string hostIP = 7;
 * @return {string}
 */
proto.ga4gh_task_exec.JobLog.prototype.getHostip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobLog.prototype.setHostip = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * repeated Ports ports = 8;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.Ports>}
 */
proto.ga4gh_task_exec.JobLog.prototype.getPortsList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.Ports>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.Ports, 8));
};


/** @param {!Array.<!proto.ga4gh_task_exec.Ports>} value */
proto.ga4gh_task_exec.JobLog.prototype.setPortsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.ga4gh_task_exec.Ports=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.Ports}
 */
proto.ga4gh_task_exec.JobLog.prototype.addPorts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.ga4gh_task_exec.Ports, opt_index);
};


proto.ga4gh_task_exec.JobLog.prototype.clearPortsList = function() {
  this.setPortsList([]);
};


