/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.JobListRequest');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.JobListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ga4gh_task_exec.JobListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.JobListRequest.displayName = 'proto.ga4gh_task_exec.JobListRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.JobListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.JobListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.JobListRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.JobListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nameprefix: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pagesize: jspb.Message.getFieldWithDefault(msg, 3, 0),
    pagetoken: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string projectID = 1;
 * @return {string}
 */
proto.ga4gh_task_exec.JobListRequest.prototype.getProjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobListRequest.prototype.setProjectid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string namePrefix = 2;
 * @return {string}
 */
proto.ga4gh_task_exec.JobListRequest.prototype.getNameprefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobListRequest.prototype.setNameprefix = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 pageSize = 3;
 * @return {number}
 */
proto.ga4gh_task_exec.JobListRequest.prototype.getPagesize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.ga4gh_task_exec.JobListRequest.prototype.setPagesize = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string pageToken = 4;
 * @return {string}
 */
proto.ga4gh_task_exec.JobListRequest.prototype.getPagetoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.JobListRequest.prototype.setPagetoken = function(value) {
  jspb.Message.setField(this, 4, value);
};


