/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.Resources');

goog.require('jspb.Message');
goog.require('proto.ga4gh_task_exec.Volume');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.Resources = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ga4gh_task_exec.Resources.repeatedFields_, null);
};
goog.inherits(proto.ga4gh_task_exec.Resources, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.Resources.displayName = 'proto.ga4gh_task_exec.Resources';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ga4gh_task_exec.Resources.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.Resources.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.Resources.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.Resources} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.Resources.toObject = function(includeInstance, msg) {
  var f, obj = {
    minimumcpucores: jspb.Message.getFieldWithDefault(msg, 1, 0),
    preemptible: jspb.Message.getFieldWithDefault(msg, 2, false),
    minimumramgb: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    volumesList: jspb.Message.toObjectList(msg.getVolumesList(),
    proto.ga4gh_task_exec.Volume.toObject, includeInstance),
    zonesList: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional uint32 minimumCpuCores = 1;
 * @return {number}
 */
proto.ga4gh_task_exec.Resources.prototype.getMinimumcpucores = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.ga4gh_task_exec.Resources.prototype.setMinimumcpucores = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bool preemptible = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ga4gh_task_exec.Resources.prototype.getPreemptible = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.ga4gh_task_exec.Resources.prototype.setPreemptible = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional double minimumRamGb = 3;
 * @return {number}
 */
proto.ga4gh_task_exec.Resources.prototype.getMinimumramgb = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.ga4gh_task_exec.Resources.prototype.setMinimumramgb = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated Volume volumes = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.Volume>}
 */
proto.ga4gh_task_exec.Resources.prototype.getVolumesList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.Volume>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.Volume, 4));
};


/** @param {!Array.<!proto.ga4gh_task_exec.Volume>} value */
proto.ga4gh_task_exec.Resources.prototype.setVolumesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ga4gh_task_exec.Volume=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.Volume}
 */
proto.ga4gh_task_exec.Resources.prototype.addVolumes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ga4gh_task_exec.Volume, opt_index);
};


proto.ga4gh_task_exec.Resources.prototype.clearVolumesList = function() {
  this.setVolumesList([]);
};


/**
 * repeated string zones = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.ga4gh_task_exec.Resources.prototype.getZonesList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 5));
};


/** @param {!Array.<string>} value */
proto.ga4gh_task_exec.Resources.prototype.setZonesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.ga4gh_task_exec.Resources.prototype.addZones = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.ga4gh_task_exec.Resources.prototype.clearZonesList = function() {
  this.setZonesList([]);
};


