/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.TaskParameter');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.TaskParameter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ga4gh_task_exec.TaskParameter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.TaskParameter.displayName = 'proto.ga4gh_task_exec.TaskParameter';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.TaskParameter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.TaskParameter} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.TaskParameter.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    location: jspb.Message.getFieldWithDefault(msg, 3, ""),
    path: jspb.Message.getFieldWithDefault(msg, 4, ""),
    pb_class: jspb.Message.getFieldWithDefault(msg, 5, ""),
    create: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string location = 3;
 * @return {string}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setLocation = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string path = 4;
 * @return {string}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setPath = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string class = 5;
 * @return {string}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setClass = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool create = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ga4gh_task_exec.TaskParameter.prototype.getCreate = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.ga4gh_task_exec.TaskParameter.prototype.setCreate = function(value) {
  jspb.Message.setField(this, 6, value);
};


