/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.Task');

goog.require('jspb.Message');
goog.require('proto.ga4gh_task_exec.DockerExecutor');
goog.require('proto.ga4gh_task_exec.Resources');
goog.require('proto.ga4gh_task_exec.TaskParameter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.Task = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ga4gh_task_exec.Task.repeatedFields_, null);
};
goog.inherits(proto.ga4gh_task_exec.Task, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.Task.displayName = 'proto.ga4gh_task_exec.Task';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ga4gh_task_exec.Task.repeatedFields_ = [4,5,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.Task.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.Task.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.Task} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.Task.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    projectid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.ga4gh_task_exec.TaskParameter.toObject, includeInstance),
    outputsList: jspb.Message.toObjectList(msg.getOutputsList(),
    proto.ga4gh_task_exec.TaskParameter.toObject, includeInstance),
    resources: (f = msg.getResources()) && proto.ga4gh_task_exec.Resources.toObject(includeInstance, f),
    dockerList: jspb.Message.toObjectList(msg.getDockerList(),
    proto.ga4gh_task_exec.DockerExecutor.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ga4gh_task_exec.Task.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Task.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string projectID = 2;
 * @return {string}
 */
proto.ga4gh_task_exec.Task.prototype.getProjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Task.prototype.setProjectid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.ga4gh_task_exec.Task.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Task.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated TaskParameter inputs = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.TaskParameter>}
 */
proto.ga4gh_task_exec.Task.prototype.getInputsList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.TaskParameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.TaskParameter, 4));
};


/** @param {!Array.<!proto.ga4gh_task_exec.TaskParameter>} value */
proto.ga4gh_task_exec.Task.prototype.setInputsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ga4gh_task_exec.TaskParameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.TaskParameter}
 */
proto.ga4gh_task_exec.Task.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ga4gh_task_exec.TaskParameter, opt_index);
};


proto.ga4gh_task_exec.Task.prototype.clearInputsList = function() {
  this.setInputsList([]);
};


/**
 * repeated TaskParameter outputs = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.TaskParameter>}
 */
proto.ga4gh_task_exec.Task.prototype.getOutputsList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.TaskParameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.TaskParameter, 5));
};


/** @param {!Array.<!proto.ga4gh_task_exec.TaskParameter>} value */
proto.ga4gh_task_exec.Task.prototype.setOutputsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.ga4gh_task_exec.TaskParameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.TaskParameter}
 */
proto.ga4gh_task_exec.Task.prototype.addOutputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.ga4gh_task_exec.TaskParameter, opt_index);
};


proto.ga4gh_task_exec.Task.prototype.clearOutputsList = function() {
  this.setOutputsList([]);
};


/**
 * optional Resources resources = 6;
 * @return {?proto.ga4gh_task_exec.Resources}
 */
proto.ga4gh_task_exec.Task.prototype.getResources = function() {
  return /** @type{?proto.ga4gh_task_exec.Resources} */ (
    jspb.Message.getWrapperField(this, proto.ga4gh_task_exec.Resources, 6));
};


/** @param {?proto.ga4gh_task_exec.Resources|undefined} value */
proto.ga4gh_task_exec.Task.prototype.setResources = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.ga4gh_task_exec.Task.prototype.clearResources = function() {
  this.setResources(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ga4gh_task_exec.Task.prototype.hasResources = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated DockerExecutor docker = 8;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.ga4gh_task_exec.DockerExecutor>}
 */
proto.ga4gh_task_exec.Task.prototype.getDockerList = function() {
  return /** @type{!Array.<!proto.ga4gh_task_exec.DockerExecutor>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ga4gh_task_exec.DockerExecutor, 8));
};


/** @param {!Array.<!proto.ga4gh_task_exec.DockerExecutor>} value */
proto.ga4gh_task_exec.Task.prototype.setDockerList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.ga4gh_task_exec.DockerExecutor=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ga4gh_task_exec.DockerExecutor}
 */
proto.ga4gh_task_exec.Task.prototype.addDocker = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.ga4gh_task_exec.DockerExecutor, opt_index);
};


proto.ga4gh_task_exec.Task.prototype.clearDockerList = function() {
  this.setDockerList([]);
};


