/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ga4gh_task_exec.Volume');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ga4gh_task_exec.Volume = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ga4gh_task_exec.Volume, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ga4gh_task_exec.Volume.displayName = 'proto.ga4gh_task_exec.Volume';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ga4gh_task_exec.Volume.prototype.toObject = function(opt_includeInstance) {
  return proto.ga4gh_task_exec.Volume.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ga4gh_task_exec.Volume} msg The msg instance to transform.
 * @return {!Object}
 */
proto.ga4gh_task_exec.Volume.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sizegb: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    source: jspb.Message.getFieldWithDefault(msg, 3, ""),
    mountpoint: jspb.Message.getFieldWithDefault(msg, 6, ""),
    readonly: jspb.Message.getFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ga4gh_task_exec.Volume.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Volume.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional double sizeGb = 2;
 * @return {number}
 */
proto.ga4gh_task_exec.Volume.prototype.getSizegb = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.ga4gh_task_exec.Volume.prototype.setSizegb = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string source = 3;
 * @return {string}
 */
proto.ga4gh_task_exec.Volume.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Volume.prototype.setSource = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string mountPoint = 6;
 * @return {string}
 */
proto.ga4gh_task_exec.Volume.prototype.getMountpoint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.ga4gh_task_exec.Volume.prototype.setMountpoint = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional bool readonly = 7;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ga4gh_task_exec.Volume.prototype.getReadonly = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 7, false));
};


/** @param {boolean} value */
proto.ga4gh_task_exec.Volume.prototype.setReadonly = function(value) {
  jspb.Message.setField(this, 7, value);
};


