<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/task_execution.proto

namespace Ga4gh_task_exec;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TaskParameter extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $description = '';
    private $location = '';
    private $path = '';
    private $class = '';
    private $create = false;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    public function getLocation()
    {
        return $this->location;
    }

    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;
    }

    public function getPath()
    {
        return $this->path;
    }

    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;
    }

    public function getClass()
    {
        return $this->class;
    }

    public function setClass($var)
    {
        GPBUtil::checkString($var, True);
        $this->class = $var;
    }

    public function getCreate()
    {
        return $this->create;
    }

    public function setCreate($var)
    {
        GPBUtil::checkBool($var);
        $this->create = $var;
    }

}

class Ports extends \Google\Protobuf\Internal\Message
{
    private $container = 0;
    private $host = 0;

    public function getContainer()
    {
        return $this->container;
    }

    public function setContainer($var)
    {
        GPBUtil::checkInt32($var);
        $this->container = $var;
    }

    public function getHost()
    {
        return $this->host;
    }

    public function setHost($var)
    {
        GPBUtil::checkInt32($var);
        $this->host = $var;
    }

}

class DockerExecutor extends \Google\Protobuf\Internal\Message
{
    private $imageName = '';
    private $cmd;
    private $workdir = '';
    private $stdin = '';
    private $stdout = '';
    private $stderr = '';
    private $ports;

    public function getImageName()
    {
        return $this->imageName;
    }

    public function setImageName($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageName = $var;
    }

    public function getCmd()
    {
        return $this->cmd;
    }

    public function setCmd(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->cmd = $var;
    }

    public function getWorkdir()
    {
        return $this->workdir;
    }

    public function setWorkdir($var)
    {
        GPBUtil::checkString($var, True);
        $this->workdir = $var;
    }

    public function getStdin()
    {
        return $this->stdin;
    }

    public function setStdin($var)
    {
        GPBUtil::checkString($var, True);
        $this->stdin = $var;
    }

    public function getStdout()
    {
        return $this->stdout;
    }

    public function setStdout($var)
    {
        GPBUtil::checkString($var, True);
        $this->stdout = $var;
    }

    public function getStderr()
    {
        return $this->stderr;
    }

    public function setStderr($var)
    {
        GPBUtil::checkString($var, True);
        $this->stderr = $var;
    }

    public function getPorts()
    {
        return $this->ports;
    }

    public function setPorts(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\Ports::class);
        $this->ports = $var;
    }

}

class Volume extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $sizeGb = 0.0;
    private $source = '';
    private $mountPoint = '';
    private $readonly = false;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getSizeGb()
    {
        return $this->sizeGb;
    }

    public function setSizeGb($var)
    {
        GPBUtil::checkDouble($var);
        $this->sizeGb = $var;
    }

    public function getSource()
    {
        return $this->source;
    }

    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;
    }

    public function getMountPoint()
    {
        return $this->mountPoint;
    }

    public function setMountPoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->mountPoint = $var;
    }

    public function getReadonly()
    {
        return $this->readonly;
    }

    public function setReadonly($var)
    {
        GPBUtil::checkBool($var);
        $this->readonly = $var;
    }

}

class Resources extends \Google\Protobuf\Internal\Message
{
    private $minimumCpuCores = 0;
    private $preemptible = false;
    private $minimumRamGb = 0.0;
    private $volumes;
    private $zones;

    public function getMinimumCpuCores()
    {
        return $this->minimumCpuCores;
    }

    public function setMinimumCpuCores($var)
    {
        GPBUtil::checkUint32($var);
        $this->minimumCpuCores = $var;
    }

    public function getPreemptible()
    {
        return $this->preemptible;
    }

    public function setPreemptible($var)
    {
        GPBUtil::checkBool($var);
        $this->preemptible = $var;
    }

    public function getMinimumRamGb()
    {
        return $this->minimumRamGb;
    }

    public function setMinimumRamGb($var)
    {
        GPBUtil::checkDouble($var);
        $this->minimumRamGb = $var;
    }

    public function getVolumes()
    {
        return $this->volumes;
    }

    public function setVolumes(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\Volume::class);
        $this->volumes = $var;
    }

    public function getZones()
    {
        return $this->zones;
    }

    public function setZones(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->zones = $var;
    }

}

class Task extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $projectID = '';
    private $description = '';
    private $inputs;
    private $outputs;
    private $resources = null;
    private $docker;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getProjectID()
    {
        return $this->projectID;
    }

    public function setProjectID($var)
    {
        GPBUtil::checkString($var, True);
        $this->projectID = $var;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    public function getInputs()
    {
        return $this->inputs;
    }

    public function setInputs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\TaskParameter::class);
        $this->inputs = $var;
    }

    public function getOutputs()
    {
        return $this->outputs;
    }

    public function setOutputs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\TaskParameter::class);
        $this->outputs = $var;
    }

    public function getResources()
    {
        return $this->resources;
    }

    public function setResources(&$var)
    {
        GPBUtil::checkMessage($var, \Ga4gh_task_exec\Resources::class);
        $this->resources = $var;
    }

    public function getDocker()
    {
        return $this->docker;
    }

    public function setDocker(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\DockerExecutor::class);
        $this->docker = $var;
    }

}

class JobListRequest extends \Google\Protobuf\Internal\Message
{
    private $projectID = '';
    private $namePrefix = '';
    private $pageSize = 0;
    private $pageToken = '';

    public function getProjectID()
    {
        return $this->projectID;
    }

    public function setProjectID($var)
    {
        GPBUtil::checkString($var, True);
        $this->projectID = $var;
    }

    public function getNamePrefix()
    {
        return $this->namePrefix;
    }

    public function setNamePrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->namePrefix = $var;
    }

    public function getPageSize()
    {
        return $this->pageSize;
    }

    public function setPageSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->pageSize = $var;
    }

    public function getPageToken()
    {
        return $this->pageToken;
    }

    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->pageToken = $var;
    }

}

class JobDesc extends \Google\Protobuf\Internal\Message
{
    private $jobID = '';
    private $state = 0;

    public function getJobID()
    {
        return $this->jobID;
    }

    public function setJobID($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobID = $var;
    }

    public function getState()
    {
        return $this->state;
    }

    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Ga4gh_task_exec\State::class);
        $this->state = $var;
    }

}

class JobListResponse extends \Google\Protobuf\Internal\Message
{
    private $jobs;
    private $nextPageToken = '';

    public function getJobs()
    {
        return $this->jobs;
    }

    public function setJobs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\JobDesc::class);
        $this->jobs = $var;
    }

    public function getNextPageToken()
    {
        return $this->nextPageToken;
    }

    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->nextPageToken = $var;
    }

}

class JobID extends \Google\Protobuf\Internal\Message
{
    private $value = '';

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;
    }

}

class JobLog extends \Google\Protobuf\Internal\Message
{
    private $cmd;
    private $startTime = '';
    private $endTime = '';
    private $stdout = '';
    private $stderr = '';
    private $exitCode = 0;
    private $hostIP = '';
    private $ports;

    public function getCmd()
    {
        return $this->cmd;
    }

    public function setCmd(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->cmd = $var;
    }

    public function getStartTime()
    {
        return $this->startTime;
    }

    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->startTime = $var;
    }

    public function getEndTime()
    {
        return $this->endTime;
    }

    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->endTime = $var;
    }

    public function getStdout()
    {
        return $this->stdout;
    }

    public function setStdout($var)
    {
        GPBUtil::checkString($var, True);
        $this->stdout = $var;
    }

    public function getStderr()
    {
        return $this->stderr;
    }

    public function setStderr($var)
    {
        GPBUtil::checkString($var, True);
        $this->stderr = $var;
    }

    public function getExitCode()
    {
        return $this->exitCode;
    }

    public function setExitCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->exitCode = $var;
    }

    public function getHostIP()
    {
        return $this->hostIP;
    }

    public function setHostIP($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostIP = $var;
    }

    public function getPorts()
    {
        return $this->ports;
    }

    public function setPorts(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\Ports::class);
        $this->ports = $var;
    }

}

class FileLog extends \Google\Protobuf\Internal\Message
{
    private $location = '';
    private $path = '';
    private $size = 0;

    public function getLocation()
    {
        return $this->location;
    }

    public function setLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->location = $var;
    }

    public function getPath()
    {
        return $this->path;
    }

    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;
    }

    public function getSize()
    {
        return $this->size;
    }

    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;
    }

}

class Job extends \Google\Protobuf\Internal\Message
{
    private $jobID = '';
    private $metadata;
    private $task = null;
    private $state = 0;
    private $logs;
    private $outputs;

    public function getJobID()
    {
        return $this->jobID;
    }

    public function setJobID($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobID = $var;
    }

    public function getMetadata()
    {
        return $this->metadata;
    }

    public function setMetadata(&$var)
    {
        $this->metadata = $var;
    }

    public function getTask()
    {
        return $this->task;
    }

    public function setTask(&$var)
    {
        GPBUtil::checkMessage($var, \Ga4gh_task_exec\Task::class);
        $this->task = $var;
    }

    public function getState()
    {
        return $this->state;
    }

    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Ga4gh_task_exec\State::class);
        $this->state = $var;
    }

    public function getLogs()
    {
        return $this->logs;
    }

    public function setLogs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\JobLog::class);
        $this->logs = $var;
    }

    public function getOutputs()
    {
        return $this->outputs;
    }

    public function setOutputs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Ga4gh_task_exec\FileLog::class);
        $this->outputs = $var;
    }

}

class ServiceInfoRequest extends \Google\Protobuf\Internal\Message
{

}

class ServiceInfo extends \Google\Protobuf\Internal\Message
{
    private $storageConfig;

    public function getStorageConfig()
    {
        return $this->storageConfig;
    }

    public function setStorageConfig(&$var)
    {
        $this->storageConfig = $var;
    }

}

class State
{
    const Unknown = 0;
    const Queued = 1;
    const Running = 2;
    const Paused = 3;
    const Complete = 4;
    const Error = 5;
    const SystemError = 6;
    const Canceled = 7;
    const Initializing = 8;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af8120a1a70726f746f2f7461736b5f657865637574696f6e2e70726f74" .
    "6f120f67613467685f7461736b5f657865631a1c676f6f676c652f617069" .
    "2f616e6e6f746174696f6e732e70726f746f22710a0d5461736b50617261" .
    "6d65746572120c0a046e616d6518012001280912130a0b64657363726970" .
    "74696f6e18022001280912100a086c6f636174696f6e180320012809120c" .
    "0a0470617468180420012809120d0a05636c617373180520012809120e0a" .
    "0663726561746518062001280822280a05506f72747312110a09636f6e74" .
    "61696e6572180120012805120c0a04686f73741802200128052297010a0e" .
    "446f636b65724578656375746f7212110a09696d6167654e616d65180120" .
    "012809120b0a03636d64180220032809120f0a07776f726b646972180320" .
    "012809120d0a05737464696e180620012809120e0a067374646f75741804" .
    "20012809120e0a0673746465727218052001280912250a05706f72747318" .
    "072003280b32162e67613467685f7461736b5f657865632e506f72747322" .
    "5c0a06566f6c756d65120c0a046e616d65180120012809120e0a0673697a" .
    "654762180220012801120e0a06736f7572636518032001280912120a0a6d" .
    "6f756e74506f696e7418062001280912100a08726561646f6e6c79180720" .
    "0128082288010a095265736f757263657312170a0f6d696e696d756d4370" .
    "75436f72657318012001280d12130a0b707265656d707469626c65180220" .
    "01280812140a0c6d696e696d756d52616d476218032001280112280a0776" .
    "6f6c756d657318042003280b32172e67613467685f7461736b5f65786563" .
    "2e566f6c756d65120d0a057a6f6e657318052003280922fd010a04546173" .
    "6b120c0a046e616d6518012001280912110a0970726f6a65637449441802" .
    "2001280912130a0b6465736372697074696f6e180320012809122e0a0669" .
    "6e7075747318042003280b321e2e67613467685f7461736b5f657865632e" .
    "5461736b506172616d65746572122f0a076f75747075747318052003280b" .
    "321e2e67613467685f7461736b5f657865632e5461736b506172616d6574" .
    "6572122d0a097265736f757263657318062001280b321a2e67613467685f" .
    "7461736b5f657865632e5265736f7572636573122f0a06646f636b657218" .
    "082003280b321f2e67613467685f7461736b5f657865632e446f636b6572" .
    "4578656375746f72225c0a0e4a6f624c6973745265717565737412110a09" .
    "70726f6a656374494418012001280912120a0a6e616d6550726566697818" .
    "022001280912100a087061676553697a6518032001280d12110a09706167" .
    "65546f6b656e180420012809223f0a074a6f6244657363120d0a056a6f62" .
    "494418012001280912250a05737461746518022001280e32162e67613467" .
    "685f7461736b5f657865632e537461746522500a0f4a6f624c6973745265" .
    "73706f6e736512260a046a6f627318012003280b32182e67613467685f74" .
    "61736b5f657865632e4a6f624465736312150a0d6e65787450616765546f" .
    "6b656e18022001280922160a054a6f624944120d0a0576616c7565180120" .
    "01280922a2010a064a6f624c6f67120b0a03636d6418012003280912110a" .
    "09737461727454696d65180220012809120f0a07656e6454696d65180320" .
    "012809120e0a067374646f7574180420012809120e0a0673746465727218" .
    "052001280912100a0865786974436f6465180620012805120e0a06686f73" .
    "74495018072001280912250a05706f72747318082003280b32162e676134" .
    "67685f7461736b5f657865632e506f72747322370a0746696c654c6f6712" .
    "100a086c6f636174696f6e180120012809120c0a04706174681802200128" .
    "09120c0a0473697a651803200128032299020a034a6f62120d0a056a6f62" .
    "494418012001280912340a086d6574616461746118022003280b32222e67" .
    "613467685f7461736b5f657865632e4a6f622e4d65746164617461456e74" .
    "727912230a047461736b18032001280b32152e67613467685f7461736b5f" .
    "657865632e5461736b12250a05737461746518042001280e32162e676134" .
    "67685f7461736b5f657865632e537461746512250a046c6f677318052003" .
    "280b32172e67613467685f7461736b5f657865632e4a6f624c6f6712290a" .
    "076f75747075747318062003280b32182e67613467685f7461736b5f6578" .
    "65632e46696c654c6f671a2f0a0d4d65746164617461456e747279120b0a" .
    "036b6579180120012809120d0a0576616c75651802200128093a02380122" .
    "140a1253657276696365496e666f52657175657374228b010a0b53657276" .
    "696365496e666f12460a0d73746f72616765436f6e66696718012003280b" .
    "322f2e67613467685f7461736b5f657865632e53657276696365496e666f" .
    "2e53746f72616765436f6e666967456e7472791a340a1253746f72616765" .
    "436f6e666967456e747279120b0a036b6579180120012809120d0a057661" .
    "6c75651802200128093a0238012a83010a055374617465120b0a07556e6b" .
    "6e6f776e1000120a0a065175657565641001120b0a0752756e6e696e6710" .
    "02120a0a065061757365641003120c0a08436f6d706c657465100412090a" .
    "054572726f721005120f0a0b53797374656d4572726f721006120c0a0843" .
    "616e63656c6564100712100a0c496e697469616c697a696e67100832d503" .
    "0a0b5461736b53657276696365126d0a0e47657453657276696365496e66" .
    "6f12232e67613467685f7461736b5f657865632e53657276696365496e66" .
    "6f526571756573741a1c2e67613467685f7461736b5f657865632e536572" .
    "76696365496e666f221882d3e493021212102f76312f6a6f62732d736572" .
    "76696365124d0a0752756e5461736b12152e67613467685f7461736b5f65" .
    "7865632e5461736b1a162e67613467685f7461736b5f657865632e4a6f62" .
    "4944221382d3e493020d22082f76312f6a6f62733a012a125f0a084c6973" .
    "744a6f6273121f2e67613467685f7461736b5f657865632e4a6f624c6973" .
    "74526571756573741a202e67613467685f7461736b5f657865632e4a6f62" .
    "4c697374526573706f6e7365221082d3e493020a12082f76312f6a6f6273" .
    "12500a064765744a6f6212162e67613467685f7461736b5f657865632e4a" .
    "6f6249441a142e67613467685f7461736b5f657865632e4a6f62221882d3" .
    "e493021212102f76312f6a6f62732f7b76616c75657d12550a0943616e63" .
    "656c4a6f6212162e67613467685f7461736b5f657865632e4a6f6249441a" .
    "162e67613467685f7461736b5f657865632e4a6f624944221882d3e49302" .
    "122a102f76312f6a6f62732f7b76616c75657d620670726f746f33"
));

