# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/task_execution.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ga4gh_task_exec.TaskParameter" do
    optional :name, :string, 1
    optional :description, :string, 2
    optional :location, :string, 3
    optional :path, :string, 4
    optional :class, :string, 5
    optional :create, :bool, 6
  end
  add_message "ga4gh_task_exec.Ports" do
    optional :container, :int32, 1
    optional :host, :int32, 2
  end
  add_message "ga4gh_task_exec.DockerExecutor" do
    optional :imageName, :string, 1
    repeated :cmd, :string, 2
    optional :workdir, :string, 3
    optional :stdin, :string, 6
    optional :stdout, :string, 4
    optional :stderr, :string, 5
    repeated :ports, :message, 7, "ga4gh_task_exec.Ports"
  end
  add_message "ga4gh_task_exec.Volume" do
    optional :name, :string, 1
    optional :sizeGb, :double, 2
    optional :source, :string, 3
    optional :mountPoint, :string, 6
    optional :readonly, :bool, 7
  end
  add_message "ga4gh_task_exec.Resources" do
    optional :minimumCpuCores, :uint32, 1
    optional :preemptible, :bool, 2
    optional :minimumRamGb, :double, 3
    repeated :volumes, :message, 4, "ga4gh_task_exec.Volume"
    repeated :zones, :string, 5
  end
  add_message "ga4gh_task_exec.Task" do
    optional :name, :string, 1
    optional :projectID, :string, 2
    optional :description, :string, 3
    repeated :inputs, :message, 4, "ga4gh_task_exec.TaskParameter"
    repeated :outputs, :message, 5, "ga4gh_task_exec.TaskParameter"
    optional :resources, :message, 6, "ga4gh_task_exec.Resources"
    repeated :docker, :message, 8, "ga4gh_task_exec.DockerExecutor"
  end
  add_message "ga4gh_task_exec.JobListRequest" do
    optional :projectID, :string, 1
    optional :namePrefix, :string, 2
    optional :pageSize, :uint32, 3
    optional :pageToken, :string, 4
  end
  add_message "ga4gh_task_exec.JobDesc" do
    optional :jobID, :string, 1
    optional :state, :enum, 2, "ga4gh_task_exec.State"
  end
  add_message "ga4gh_task_exec.JobListResponse" do
    repeated :jobs, :message, 1, "ga4gh_task_exec.JobDesc"
    optional :nextPageToken, :string, 2
  end
  add_message "ga4gh_task_exec.JobID" do
    optional :value, :string, 1
  end
  add_message "ga4gh_task_exec.JobLog" do
    repeated :cmd, :string, 1
    optional :startTime, :string, 2
    optional :endTime, :string, 3
    optional :stdout, :string, 4
    optional :stderr, :string, 5
    optional :exitCode, :int32, 6
    optional :hostIP, :string, 7
    repeated :ports, :message, 8, "ga4gh_task_exec.Ports"
  end
  add_message "ga4gh_task_exec.FileLog" do
    optional :location, :string, 1
    optional :path, :string, 2
    optional :size, :int64, 3
  end
  add_message "ga4gh_task_exec.Job" do
    optional :jobID, :string, 1
    map :metadata, :string, :string, 2
    optional :task, :message, 3, "ga4gh_task_exec.Task"
    optional :state, :enum, 4, "ga4gh_task_exec.State"
    repeated :logs, :message, 5, "ga4gh_task_exec.JobLog"
    repeated :outputs, :message, 6, "ga4gh_task_exec.FileLog"
  end
  add_message "ga4gh_task_exec.ServiceInfoRequest" do
  end
  add_message "ga4gh_task_exec.ServiceInfo" do
    map :storageConfig, :string, :string, 1
  end
  add_enum "ga4gh_task_exec.State" do
    value :Unknown, 0
    value :Queued, 1
    value :Running, 2
    value :Paused, 3
    value :Complete, 4
    value :Error, 5
    value :SystemError, 6
    value :Canceled, 7
    value :Initializing, 8
  end
end

module Ga4ghTaskExec
  TaskParameter = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.TaskParameter").msgclass
  Ports = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.Ports").msgclass
  DockerExecutor = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.DockerExecutor").msgclass
  Volume = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.Volume").msgclass
  Resources = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.Resources").msgclass
  Task = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.Task").msgclass
  JobListRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.JobListRequest").msgclass
  JobDesc = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.JobDesc").msgclass
  JobListResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.JobListResponse").msgclass
  JobID = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.JobID").msgclass
  JobLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.JobLog").msgclass
  FileLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.FileLog").msgclass
  Job = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.Job").msgclass
  ServiceInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.ServiceInfoRequest").msgclass
  ServiceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.ServiceInfo").msgclass
  State = Google::Protobuf::DescriptorPool.generated_pool.lookup("ga4gh_task_exec.State").enummodule
end
